# Generated by Django 4.0.1 on 2022-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='i_watched',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='o_watched',
        ),
        migrations.AddField(
            model_name='movie',
            name='i_watched_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='o_watched_date',
            field=models.DateField(null=True),
        ),
    ]
